---
title: "On the use of command line tools"
description: |
  Using `AWK` to parse court calendars
author:
  - name: Michael DeWitt
    url: https://michaeldewittjr.com
date: 06-22-2019
categories:
  - CLI
  - awk
  - sed
  - bash
draft: FALSE
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

What always amazes me is that years ago when memory was scarce and computational power was expensive, tools were developed to parse and manipulate data that fit these restrictions. Among these tools you find things like `AWK`, `SED`, and the `bourne` shell. I have begun to appreciate these tools for facilitating data work.

## A motivating examples

The Winston-Salem county court house publishes the court calendar roughly once a week. Unfortunately, the file that is made available is a terrible line-printed file. The data are not structured in a nice form, so it requires some parsing if one wants to do any kind of analysis on it. 

This becomes especially challenging if you have a lot of data (which in this case I do), with many files over several years. This is a great opportunity to use our friends from `AWK` to help parse and wrangle these data.

### Data Example

Below is a picture of the data file. As you can see there is some repeatability with line spacing, but basically free form text.


```{bash}
head -n 40 court.txt
```

### Parsing the Defendant Names

Here I am going to use `AWK` to use five spaces as the file separator, the pull the first record on each line (here the line with details about the case and the defendant). I then pipe this to another `AWK` line where I pull out the second, third, and fourth words and tab delineate them. Additionally, I remove any blank lines.

```{bash}

cat court.txt | awk 'BEGIN{ FS = "      "} $1 ~ /,/ {print $1}' | 
awk '$1 ~ /,/ NF {print $2 $3 "\t" $4}' |
awk 'NF > 0' > defendants

head defendants
```

I can then do something similar to parse the complainants. 

```{bash}
cat court.txt | awk 'BEGIN{ FS = " "} $5 ~ /,/ {print $5}' > complaints 
```

See below.

```{bash}
head complaints
```

Now I can read them in and parse them together
